quarkus.http.host=0.0.0.0
quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://db:5432/inventory_db}
##quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
#quarkus.log.category."org.hibernate.SQL".level=INFO

quarkus.log.level=INFO
#quarkus.log.category."io.smallrye.jwt".level=DEBUG
###############################
### RABBITMQ
###############################3
mp.messaging.connector.smallrye-rabbitmq.host=rabbitmq
mp.messaging.connector.smallrye-rabbitmq.port=5672
mp.messaging.connector.smallrye-rabbitmq.username=guest
mp.messaging.connector.smallrye-rabbitmq.password=guest
quarkus.log.category."io.smallrye.reactive.messaging.rabbitmq".level=DEBUG


mp.messaging.outgoing.product-events-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.product-events-out.exchange.name=product-exchange
mp.messaging.outgoing.product-events-out.routing-key=product.created


# Reservation events
mp.messaging.incoming.reservationcreated-events-in.connector=smallrye-rabbitmq
mp.messaging.incoming.reservationcreated-events-in.exchange.name=reservation-exchange
mp.messaging.incoming.reservationcreated-events-in.exchange.type=topic
mp.messaging.incoming.reservationcreated-events-in.queue.name=reservation-created
mp.messaging.incoming.reservationcreated-events-in.routing-keys=reservation.created
mp.messaging.incoming.reservationcreated-events-in.exchange.declare=true

# Reservation expired
mp.messaging.incoming.reservationexpired-events-in.connector=smallrye-rabbitmq
mp.messaging.incoming.reservationexpired-events-in.exchange.name=reservationexpired-exchange
mp.messaging.incoming.reservationexpired-events-in.exchange.type=topic
mp.messaging.incoming.reservationexpired-events-in.queue.name=reservationexpired-created
mp.messaging.incoming.reservationexpired-events-in.routing-keys=reservationexpired.created
mp.messaging.incoming.reservationexpired-events-in.exchange.declare=true



# purchase events
mp.messaging.incoming.purchasecreated-events-in.connector=smallrye-rabbitmq
mp.messaging.incoming.purchasecreated-events-in.exchange.name=purchase-exchange
mp.messaging.incoming.purchasecreated-events-in.exchange.type=topic
mp.messaging.incoming.purchasecreated-events-in.queue.name=ai-purchase-created
mp.messaging.incoming.purchasecreated-events-in.routing-keys=purchase.created


mp.messaging.incoming.purchase-events-in.connector=smallrye-rabbitmq
mp.messaging.incoming.purchase-events-in.exchange.name=purchase-exchange
mp.messaging.incoming.purchase-events-in.exchange.type=topic
mp.messaging.incoming.purchase-events-in.queue.name=purchase-created-queue
mp.messaging.incoming.purchase-events-in.routing-keys=purchase.created
mp.messaging.incoming.purchase-events-in.exchange.declare=true
mp.messaging.incoming.purchase-events-in.queue.declare=true


########################################
# JWT SIGNING (PRIVATE KEY)
########################################
# Absolute or relative path to private PEM
#smallrye.jwt.sign.key.location=keys/privateKey.pem

# Algorithm used to sign tokens
#smallrye.jwt.sign.algorithm=RS256

########################################
# JWT VERIFICATION (PUBLIC KEY)
########################################
# Public key used to verify incoming tokens
# JWT
#mp.jwt.verify.publickey.location=/deployments/keys/publicKey.pem
#quarkus.log.category."io.smallrye.jwt".level=DEBUG
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
#smallrye.jwt.sign.key.location=/deployments/keys/privateKey.pem


########################################
# JWT GENERAL SETTINGS
########################################
# Optional but recommended
mp.jwt.verify.audiences=quarkus-api

########################################
# Security (optional defaults)
########################################
quarkus.security.auth.enabled=true

###########################
# METRICS
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true

# Exponer endpoint
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.jvm.enabled=true

# Path de métricas
quarkus.micrometer.export.prometheus.path=/q/metrics
###############
# KAFKA
################
# Kafka bootstrap

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true

#mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=auth-service

quarkus.redis.hosts=redis://redis:6379

##SWAGGER##
#%dev.quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.always-include=true

# Enable Swagger UI
quarkus.swagger-ui.always-include=true

# Custom path
quarkus.swagger-ui.path=/swagger

# Theme (optional)
quarkus.swagger-ui.theme=flattop

# Show request duration
quarkus.swagger-ui.display-request-duration=true

# Show operation IDs
quarkus.swagger-ui.display-operation-id=true
quarkus.swagger-ui.always-include=true
#######
## LOGS
##########
quarkus.log.console.json=true
quarkus.log.console.json.pretty-print=false
# Include useful fields
quarkus.log.console.json.additional-field.service.name=inventory-service
quarkus.log.console.json.additional-field.service.version=1.0.0

inventory.api.key=${INVENTORY_API_KEY}

quarkus.log.console.json=false

