quarkus.http.host=0.0.0.0
quarkus.http.port=8080


quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DATABASE_USERNAME:postgres}
quarkus.datasource.password=${DATABASE_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/inventory_db}
##quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
#quarkus.log.category."org.hibernate.SQL".level=INFO

quarkus.log.level=INFO
#quarkus.log.category."io.smallrye.jwt".level=DEBUG
###############################
### RABBITMQ
###############################3
rabbitmq-host=${RABBITMQ_HOST:rabbitmq}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:guest}
rabbitmq-password=${RABBITMQ_PASSWORD:guest}
rabbitmq-ssl=${RABBITMQ_TLS:false}


mp.messaging.connector.smallrye-rabbitmq.host=${rabbitmq-host}
mp.messaging.connector.smallrye-rabbitmq.port=${rabbitmq-port}
mp.messaging.connector.smallrye-rabbitmq.username=${rabbitmq-username}
mp.messaging.connector.smallrye-rabbitmq.password=${rabbitmq-password}

mp.messaging.outgoing.product-events-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.product-events-out.exchange.name=product-exchange
mp.messaging.outgoing.product-events-out.routing-key=product.created

mp.messaging.incoming.product-events-in.connector=smallrye-rabbitmq
mp.messaging.incoming.product-events-in.queue.name=product-queue
mp.messaging.incoming.product-events-in.exchange.name=product-exchange
mp.messaging.incoming.product-events-in.exchange.type=topic

mp.messaging.outgoing.reservation-events-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.reservation-events-out.exchange.name=reservation-exchange
mp.messaging.outgoing.reservation-events-out.exchange.type=topic
mp.messaging.outgoing.reservation-events-out.routing-key=reservation.created
mp.messaging.outgoing.reservation-events-out.default-routing-key=reservation.created
mp.messaging.outgoing.reservation-events-out.exchange.declare=true

mp.messaging.outgoing.reservation-expired-events-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.reservation-expired-events-out.exchange.name=reservationexpired-exchange
mp.messaging.outgoing.reservation-expired-events-out.exchange.type=topic
mp.messaging.outgoing.reservation-expired-events-out.routing-key=reservationexpired.created
mp.messaging.outgoing.reservation-expired-events-out.default-routing-key=reservationexpired.created
mp.messaging.outgoing.reservation-expired-events-out.exchange.declare=true

mp.messaging.outgoing.purchase-events-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.purchase-events-out.exchange.name=purchase-exchange
mp.messaging.outgoing.purchase-events-out.exchange.type=topic
mp.messaging.outgoing.purchase-events-out.routing-key=purchase.created
mp.messaging.outgoing.purchase-events-out.default-routing-key=purchase.created
mp.messaging.outgoing.purchase-events-out.exchange.declare=true

########################################
# JWT SIGNING (PRIVATE KEY)
########################################
# Absolute or relative path to private PEM
#smallrye.jwt.sign.key.location=keys/privateKey.pem

# Algorithm used to sign tokens
#smallrye.jwt.sign.algorithm=RS256

########################################
# JWT VERIFICATION (PUBLIC KEY)
########################################
# Public key used to verify incoming tokens
# JWT
#mp.jwt.verify.publickey.location=/deployments/keys/publicKey.pem
#quarkus.log.category."io.smallrye.jwt".level=DEBUG
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
#smallrye.jwt.sign.key.location=/deployments/keys/privateKey.pem


########################################
# JWT GENERAL SETTINGS
########################################
# Optional but recommended
mp.jwt.verify.audiences=quarkus-api

########################################
# Security (optional defaults)
########################################
quarkus.security.auth.enabled=true

###########################
# METRICS
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true

# Exponer endpoint
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.jvm.enabled=true

# Path de métricas
quarkus.micrometer.export.prometheus.path=/q/metrics
###############
# KAFKA
################
# Kafka bootstrap
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}

kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=AWS_MSK_IAM
kafka.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
kafka.sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler



quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true

#mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=auth-service

#quarkus.redis.hosts=redis://redis:6379

#quarkus.redis.hosts=${REDIS_URL}
#quarkus.redis.username=${REDIS_USERNAME}
#quarkus.redis.password=${REDIS_PASSWORD}

quarkus.redis.hosts=${REDIS_HOST:redis://redis:6379}

##SWAGGER##
#%dev.quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.always-include=true

# Enable Swagger UI
quarkus.swagger-ui.always-include=true

# Custom path
quarkus.swagger-ui.path=/swagger

# Theme (optional)
quarkus.swagger-ui.theme=flattop

# Show request duration
quarkus.swagger-ui.display-request-duration=true

# Show operation IDs
quarkus.swagger-ui.display-operation-id=true
quarkus.swagger-ui.always-include=true
#######
## LOGS
##########
quarkus.log.console.json=true
quarkus.log.console.json.pretty-print=false
# Include useful fields
quarkus.log.console.json.additional-field.service.name=inventory-service
quarkus.log.console.json.additional-field.service.version=1.0.0

inventory.api.key=${APP_API_KEY:dev-local-key}

quarkus.log.console.json=false

